# Generated by Django 2.2.28 on 2025-03-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiztopia', '0002_auto_20250307_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
